version: '3'

services:
  generator:
    image: 35.188.35.68:55000/generator:ci-${GENERATOR_BUILD_NUMBER-9}
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8081:8025"
