version: '3.1'

services:
  generator:
    image: 35.188.35.68:55000/generator:ci-5
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  integration:
    image: 35.188.35.68:55000/generator:integration-5
    build: .

